CREATE USER 'usr'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON *.* TO 'usr'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

# create database if not exists pcw;
CREATE DATABASE IF NOT EXISTS pcw
    CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_unicode_ci;

use pcw;

CREATE TABLE SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
) ENGINE=InnoDB
  ROW_FORMAT=DYNAMIC
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
   SESSION_PRIMARY_ID CHAR(36) NOT NULL,
   ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
   ATTRIBUTE_BYTES BLOB NOT NULL,
   CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
   CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
) ENGINE=InnoDB
  ROW_FORMAT=DYNAMIC
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

create table if not exists user
(
    uid int auto_increment
        primary key,
    email varchar(255) not null,
    username varchar(255) not null,
    password varchar(255) not null,
    constraint user_pk2
        unique (username),
    constraint user_pk3
        unique (email),
    CONSTRAINT chk_username_length CHECK (CHAR_LENGTH(username) >= 6),
    CONSTRAINT chk_email_length CHECK (CHAR_LENGTH(email) >= 6)
) engine=innodb
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  comment '用户表';

CREATE TABLE IF NOT EXISTS goods_info
(
    goods_id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '商品id',
    goods_name VARCHAR(255) NOT NULL COMMENT '商品名称',
    goods_spec VARCHAR(255) COMMENT '规格',
    goods_price VARCHAR(255) COMMENT '价格',
    goods_img_url VARCHAR(255) NOT NULL COMMENT '图片URL',
    goods_url VARCHAR(255) NOT NULL COMMENT '商品链接'
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='商品信息表';

CREATE TABLE IF NOT EXISTS goods_history_price (
   good_id INT UNSIGNED NOT NULL,
   price_history JSON NOT NULL,
   PRIMARY KEY (good_id),
   CONSTRAINT fk_goods_id FOREIGN KEY (good_id) REFERENCES goods_info(goods_id) ON DELETE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='商品历史价格表';